# Generated by Django 5.1.6 on 2025-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='isfollow',
            field=models.BooleanField(default=False),
        ),
    ]
