# Generated by Django 5.1.6 on 2025-03-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow_isfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='isfollow',
        ),
    ]
