# Generated by Django 5.1.6 on 2025-03-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_posts_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='liked_by',
        ),
    ]
