# Generated by Django 5.1.6 on 2025-03-22 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_posts_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likedpost', to=settings.AUTH_USER_MODEL),
        ),
    ]
